app/build.gradle.kts
app/src/androidTest/java/com/android/partagix/ExampleInstrumentedTest.kt
app/src/androidTest/java/com/android/partagix/screen/MainScreen.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/partagix/MainActivity.kt
app/src/main/java/com/android/partagix/SecondActivity.kt
app/src/main/java/com/android/partagix/SimpleData.kt
app/src/main/java/com/android/partagix/resources/C.kt
app/src/main/java/com/android/partagix/ui/theme/Color.kt
app/src/main/java/com/android/partagix/ui/theme/Theme.kt
app/src/main/java/com/android/partagix/ui/theme/Type.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/test/java/com/android/partagix/ExampleRobolectricTest.kt
app/src/test/java/com/android/partagix/ExampleUnitTest.kt
app/src/test/java/com/android/partagix/PointTest.kt
app/src/test/java/com/android/partagix/screen/SecondScreen.kt

The default package name was "sample", which is clearly wrong...

Refactored app package: sample to partagix

---

.github/workflows/ci.yml
app/build.gradle.kts
app/src/androidTest/java/com/android/partagix/ExampleInstrumentedTest.kt
app/src/androidTest/java/com/android/partagix/screen/MainScreen.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/partagix/MainActivity.kt
app/src/main/java/com/android/partagix/SecondActivity.kt
app/src/main/java/com/android/partagix/SimpleData.kt
app/src/main/java/com/android/partagix/model/auth/Authentication.kt
app/src/main/java/com/android/partagix/resources/C.kt
app/src/main/java/com/android/partagix/ui/theme/Color.kt
app/src/main/java/com/android/partagix/ui/theme/Theme.kt
app/src/main/java/com/android/partagix/ui/theme/Type.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/test/java/com/android/partagix/ExampleRobolectricTest.kt
app/src/test/java/com/android/partagix/ExampleUnitTest.kt
app/src/test/java/com/android/partagix/PointTest.kt
app/src/test/java/com/android/partagix/screen/SecondScreen.kt
build.gradle.kts

Added firebase auth (google sign in) + button in the main file to test it
By mistake I also added the commit of renaming...

Added Authentication

---

app/src/androidTest/java/com/android/partagix/home/HomeTest.kt
app/src/androidTest/java/com/android/partagix/screens/HomeScreen.kt
app/src/main/java/com/android/partagix/ui/screens/HomeScreen.kt

Add a testing screen and some tests for the current home screen. 
-> Will have to be modified when the home screen will be implemented entirely.

Home screen tests

---

app/src/androidTest/java/com/android/partagix/authentication/BootTest.kt
app/src/main/java/com/android/partagix/model/Database.kt
app/src/main/java/com/android/partagix/model/ItemViewModel.kt
app/src/main/java/com/android/partagix/model/item/Item.kt
app/src/main/java/com/android/partagix/ui/components/ItemList.kt
app/src/main/java/com/android/partagix/ui/components/ItemUi.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryCreateItem.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryCreateOrEditItemScreen.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt

inventory made no sens on the database, and item can only belong to one user and no more
There is also a fix to the location to insert it on the db

Remove inventory from database

---

.github/workflows/ci.yml
app/build.gradle.kts

I try different things to make SonarCloud work

Make SonarCloud work

---

app/src/main/java/com/android/partagix/ui/components/LabeledText.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt

Change the UI of View Item, so it doesn't feel like we can change it

Cl/fix UI view item

---

app/src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt

When a user clic an on item we display the save button only if the user is the owner of the said item

Fix issue #130

---

app/src/androidTest/java/com/android/partagix/inventory/InventoryCreateOrEditTest.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryTest.kt
app/src/androidTest/java/com/android/partagix/navigation/EndToEnd.kt
app/src/main/java/com/android/partagix/model/visibility/Visibility.kt
app/src/main/java/com/android/partagix/ui/components/DropDown.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryCreateOrEditItemScreen.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt

Added a visibilityLabel field to items of Visibility, in order to have a clean dissociated String between the UI information and the DB implementation.
Modified linked call.
Deleted unused val in InventoryViewItem.kt.

Added a visibilityLabel field to Visibility item.

---

app/src/androidTest/java/com/android/partagix/components/FilterTest.kt

The Filter component has now a lot of tests, which should greatly improve branch coverage.

Adding simple tests for Filter 

---

app/src/androidTest/java/com/android/partagix/components/LabeledText.kt
app/src/androidTest/java/com/android/partagix/components/LabeledTextTest.kt
app/src/main/java/com/android/partagix/ui/components/LabeledText.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt

Implemented UI test for this small component.

LabeledTextTest implementation

---

app/src/androidTest/java/com/android/partagix/LoanViewModelTests.kt
app/src/androidTest/java/com/android/partagix/loan/LoanTest.kt
app/src/androidTest/java/com/android/partagix/model/FilteringTest.kt
app/src/main/java/com/android/partagix/model/InventoryViewModel.kt
app/src/main/java/com/android/partagix/model/LoanViewModel.kt
app/src/main/java/com/android/partagix/model/auth/Authentication.kt
app/src/main/java/com/android/partagix/model/filtering/Filtering.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/screens/LoanScreen.kt

The LoanScreen has now a proper LoanViewModel, fully tested.

Adding the backend for Loans

---

app/src/androidTest/java/com/android/partagix/home/HomeTest.kt
app/src/androidTest/java/com/android/partagix/qr/qrTest.kt
app/src/androidTest/java/com/android/partagix/screens/QrScanScreen.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/navigation/NavigationActions.kt
app/src/main/java/com/android/partagix/ui/screens/HomeScreen.kt
app/src/main/java/com/android/partagix/ui/screens/QrScanScreen.kt

I implemented the functionalities of the 3 buttons on the home screen. The "quick scan" button redirect on a sample screen until the real QrScanScreen is implemented.

Home screen buttons functionalities 

---

.github/workflows/ci.yml
app/build.gradle.kts
app/src/androidTest/java/com/android/partagix/home/HomeTest.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryCreateOrEditTest.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryTest.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryViewTest.kt
app/src/androidTest/java/com/android/partagix/loan/LoanTest.kt
app/src/androidTest/java/com/android/partagix/stamp/StampTest.kt
app/src/androidTest/java/com/android/partagix/viewAccount/ViewAccountTest.kt
gradle.properties

Currently, the CI takes 15min and 40min, which is huge. The purpose of this PR is to make it really faster !

Optimizing CI

---

app/src/androidTest/java/com/android/partagix/inventory/EndToEndCreateEdit.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryCreateOrEditTest.kt
app/src/androidTest/java/com/android/partagix/navigation/EndToEnd.kt
app/src/main/java/com/android/partagix/model/ItemViewModel.kt
app/src/main/java/com/android/partagix/ui/components/DropDown.kt

- Updated some tests to fit new behaviour
- Made a more usefull list of categories

Added default category "others"

---

.github/workflows/ci.yml
app/build.gradle.kts
gradle.properties

The new CI config seems to add randomness on some tests, making them fail from time to time. This is an attempt to fix it.

Reverting old CI settings

---

README.md

It seems that sonar has a quickly evolving API. This PR should make it more flexible.

Fixed the line coverage badge

---

app/src/main/java/com/android/partagix/ui/App.kt

Add a loanViewModel.getAvailableLoans() call at launch.
Removed obsolete comments.

Fix Loan loading at start

---

app/src/main/java/com/android/partagix/ui/screens/StampScreen.kt

The Label textField input was unreadable.

StampScreen fix unreadable textField

---

app/src/androidTest/java/com/android/partagix/components/ImagePickerTest.kt
app/src/main/java/com/android/partagix/ui/components/ImagePicker.kt

As suggested in https://github.com/EPFLSWENT2024G1/partagix/pull/169#pullrequestreview-2037012084.

Added a test in image picker

---

app/src/main/java/com/android/partagix/model/Database.kt

Also delete item_loan private val, that isn't used, and doesn't exist in the database neither.

Modify the storage and research of "loanstate" to "loan_state", for naming conventions.

---

app/src/androidTest/java/com/android/partagix/LoanViewModelTests.kt
app/src/androidTest/java/com/android/partagix/loan/LoanTest.kt
app/src/androidTest/java/com/android/partagix/login/LoginTest.kt
app/src/androidTest/java/com/android/partagix/qr/onQrScannedTest.kt
app/src/main/java/com/android/partagix/model/LoanViewModel.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/components/ItemList.kt
app/src/main/java/com/android/partagix/ui/components/ItemUi.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryScreen.kt
app/src/main/java/com/android/partagix/ui/screens/LoanScreen.kt

The inventory screen is cleaner now, closer to the figma design.
The Loan Screen had some visual imperfections, as pointed out by @Mass-14. They are fixed in this Pull Requests. 
Also, the names of the users that have available items to be loaned were not displayed correctly on the Loan Screen. This feature is now fully integrated.

Inventory Screen: better UI + Loan Screen bug fixes

---

app/src/androidTest/java/com/android/partagix/DatabaseTests.kt
app/src/main/java/com/android/partagix/model/Database.kt
app/src/main/java/com/android/partagix/model/rating/Rating.kt

Implements 3 database methods concerning the reviews :
-  getComments() does go through every loan to return a List containing every comment on a user, as well as the author of this comment.
- newAveragRank() computes the average rank received by a user, and stores it in the User table.
- setReview() stores a given review in the database fields.

Database review and comment functions.

---

app/src/androidTest/java/com/android/partagix/DatabaseTests.kt
app/src/androidTest/java/com/android/partagix/borrow/BorrowTest.kt
app/src/androidTest/java/com/android/partagix/inventory/EndToEndCreateEdit.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryViewTest.kt
app/src/androidTest/java/com/android/partagix/screens/BorrowScreen.kt
app/src/main/java/com/android/partagix/model/BorrowViewModel.kt
app/src/main/java/com/android/partagix/model/Database.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/navigation/NavigationActions.kt
app/src/main/java/com/android/partagix/ui/screens/BorrowScreen.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt

This implements the backend, the frontend and the tests for the creation of borrow requests (outgoing requests).

Create outgoing requests

---

app/src/main/java/com/android/partagix/ui/App.kt

this pr fix the fact that if you refuse to give your geolocalisation it won't ask another time when you go to another screen

fixing the geolocalisation ask 

---

app/src/main/java/com/android/partagix/model/LoanViewModel.kt
app/src/main/java/com/android/partagix/ui/components/Filter.kt
app/src/main/java/com/android/partagix/ui/screens/LoanScreen.kt

There was a problem on the filters, now quantity and location works together and they keep their state when we change screen

Fix filter on loan screen

---

app/src/androidTest/java/com/android/partagix/screens/StampScreen.kt
app/src/androidTest/java/com/android/partagix/stamp/StampTest.kt
app/src/main/java/com/android/partagix/ui/screens/StampScreen.kt

- add the BottomBar
- remove "dimension" text
- remove "label" text
- clean spacings

Fixed the StampScreen according to the figma.

---

app/src/androidTest/java/com/android/partagix/DatabaseTests.kt
app/src/androidTest/java/com/android/partagix/LoanViewModelTests.kt
app/src/androidTest/java/com/android/partagix/ManageViewModelTest.kt
app/src/main/java/com/android/partagix/model/Database.kt
app/src/main/java/com/android/partagix/model/LoanViewModel.kt
app/src/main/java/com/android/partagix/model/ManageLoanViewModel.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/screens/BorrowScreen.kt

Fix [#263](https://github.com/EPFLSWENT2024G1/partagix/issues/263)
Only forbid the creation of loan when item unavailable without displaying error

Block concurrent loans

---

.github/workflows/apk_build.yml
.github/workflows/ci.yml

In the loan screen, Maps is not loading, due to a missing api key. The workflow `APK Build` should take care of that, but currently has a bug in it

Fixing APK Build

---

app/src/main/java/com/android/partagix/ui/App.kt

There where 2 call to database that are heavy and make the app way slower

Remove useless call to database

---

app/src/main/java/com/android/partagix/ui/screens/InventoryScreen.kt
app/src/main/java/com/android/partagix/ui/screens/ManageLoanRequestScreen.kt
app/src/main/java/com/android/partagix/ui/screens/ManageOutgoingLoan.kt
app/src/main/java/com/android/partagix/ui/screens/OldLoansScreen.kt

Renamed to History

---

app/src/main/java/com/android/partagix/model/InventoryViewModel.kt

Added ongoing loans to the list of borrowed items.

Fix borrowed items filtering with ongoing loans.

---

app/src/androidTest/java/com/android/partagix/ManageViewModelTest.kt
app/src/androidTest/java/com/android/partagix/inventory/EndToEndCreateEdit.kt
app/src/androidTest/java/com/android/partagix/inventory/InventoryTest.kt
app/src/main/java/com/android/partagix/model/ManageLoanViewModel.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/components/ItemListSeparator.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryScreen.kt

In this PR I commented the number indicating the number of Incoming/Outgoing requests in the Inventory Screen. (#274)
I restored those in this PR.

Cl/restore commented UI elements

---

app/src/main/java/com/android/partagix/ui/screens/InventoryCreateOrEditItemScreen.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryScreen.kt
app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt

In Create/Edit screen, some fields have a strange behaviour when a long string is entered, fix this.
The rounded corners image border, overlap the square image, remove them.

Fix UI details

---

app/build.gradle.kts
app/src/androidTest/java/com/android/partagix/BarcodeAnalyzerTest.kt
app/src/androidTest/java/com/android/partagix/FirebaseStorageTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/partagix/model/BarecodeAnalyzer.kt
app/src/main/java/com/android/partagix/ui/App.kt
app/src/main/java/com/android/partagix/ui/screens/HomeScreen.kt

On clic on the wuick scan button now we open directly the camera inside the app which makes the navigation way better because we can stay inside the app for the whole process

Scan directly in app

---

app/src/main/java/com/android/partagix/ui/screens/InventoryCreateOrEditItemScreen.kt

Modified when updating the uiState instead of parameter in textfield

 Default quantity fix

---

app/src/main/java/com/android/partagix/model/InventoryViewModel.kt

The issue was a missing update of the uiState of a loan that is in an ongoing state, the ui code was correct.

Infos button on borrowed items fix
